remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: BCFier For Renga
description: BCFier for Renga is an extendible and Open Source BCF client.

show_downloads: true
github:
  zip_url: https://github.com/tyan/BCFierForRenga/releases/download/BCFierForRenga_v0.1/BCFier.zip
  another_url: https://github.com/tyan/BCFierForRenga/releases/download/BCFierForRenga_v0.1/BCFier.Win.zip